language: node_js
node_js: 12
before_install:
- npm install -g npm@latest
install:
- npm install
script:
- npm run lint
- npm run test
- npm run build
after_success:
- npm run semantic-release
- codecov
env:
  global:
  # NPM_TOKEN
  - secure: UOFOESGx8y+qGnNmLReNPcYAKYxwnkODisxCP5b7DgBJGbLN8h03Ik8n/LDEZlFpwfl3CbE3piWHDWyXW4IysULxaggglKXP1WQ2e2mwU1s33L8qf2X1tiW33zCiGDRExsEQwAWX5YCS6uqg1cLiZYS+gYqxRhXuGGLzSCYK/NvKnqaxsRY/DNTe9eH6xM4pLQt3/+1qOUgdhZlzc+E9JaMqFhtxxp+L1tadZ63KjCpsyWw4//Rb3z4khk0NcjJ0nW0B8VL4DKTNfqdkudThqDBOPMOGLZxE9sa9xiPattYoYxaDDPXiMzmUAK8KoHjhv6j6EuLewx0QSjsRf+fHYy5n/tHllVF0V6awnl1xuiDUXZI3LQV09//RkoQi/+vdUd7RbHDnNMaf3YQIkVNeCL1doiSS+uCjk1GxqUW2b+8g1RmugOj2F9XJClCB8d+75WlwxRGytuuN0VQUWi60LEiNFSU3f+AEuayy686iCZxvtahu37iWMbbaDt8vcUYTH7RYQq8OrDMRFErJpr0vEEVO2FqPrpVoR5fVXfpMox3L2jhylR0cwKevh/eiy/yGxRhnTcRJYn3D4pJMKDxu6ELOakKpNhDN+EhBfbwNcMZwbdNc0GCWSn6TavNArPFQaWocpSXPitBbTAHLZFxwcmBamHhHoIIZRWe1F3bZaLw=
  # GH_TOKEN - for the edx-semantic-release github user
  - secure: p+ktBwlNBlPOwG/VdA5Fu2+Yy12vZowPY6e9672xSxXMkM7WvoV+nGkfyN28Rxqdwlp/uqhrD30EQluFEhhowtVqTVueGgLkUL6K2lJD/dZ/7l9fJMJsfBsb+lbri7nBEAFexb30OzpBHPVWb5ool0t9x+lpkijIMYU397qXGrBF/ooS5k6+sdksTxP+299nWBFvwwj5iSZ0P7DzUS2f8IyWt4uS6uRCeuIBGFVeqj6Y/pFF9kD5rlcQ9wHf47LRkNTHJxVsGiO+t/BL1urMIO6xri4W+v25moJuanUgejy4cq8DJ+rRWNSZkKDbQi80SI8V6B4dX+Y+9TQpt54zfh/24cn3D9SCGyiyoxtnC6oxhJcDmAN/fzrpQWo4GkIsAUXMIL3pii6RAJO+WyP5vaqEMFKnUr68kOGH5QCiRwD60pZuP/lcn4rActVUca3VmQTlANLVc92vKK6T1dPF1mAgycPZKLS3AGNyNrqj6H5SKxB/K2GOC7PX87kV2+4f0GMfxqymC0W5arep4wGUfmoX4tHVlhy8Z+8HITfaTz+CjjQyEZHXtlHgFwpQ6/6IYyrdwNf5JWHvm2EdpGu2Xh2CtGhOxqC/eGse+YG3CPKpWsn3L9MPg1JguvFiHGGlhXRRK/BAeg72iZo0OQt53jBOn27VWKZWn2NPH7lvhWk=
